{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aurora-gov.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aurora-gov.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}