{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora-gov.postgresql.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aurora-gov.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "aurora-gov.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}