{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurora-gov.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aurora-gov.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ include "aurora-gov.phoenix.secretKeyBase" . | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ include "aurora-gov.postgresql.password" . | b64enc | quote }}
  projector-database-url: {{ include "aurora-gov.postgresql.projectorUrl" . | b64enc | quote }}
  eventstore-database-url: {{ include "aurora-gov.postgresql.eventstoreUrl" . | b64enc | quote }}
  {{- end }}
{{- end }}